image: node:16.13.1

stages:
    - install
    - build
    - lint 
    - test
    - trigger
    - pages-deploy

cache:
    paths:
        - node_modules/

install-job:
    stage: install
    script:
        - echo "Installing dependencies..."
        - yarn install
        - echo "Installed dependencies."

build-job:
    stage: build
    script:
        - echo "Compiling *.md"
        - yarn run build
        - echo "Compiled *.md to build/*.html."
    artifacts:
        paths:
            - build/ 
 
lint-job:
    stage: lint
    needs:
      - build-job
    script:
        - echo "Linting code..."
        - yarn run lint
        - yarn run prettier
        - echo "No lint issues found."

test-job:
    stage: test
    needs:
      - build-job
    script:
        - echo "Running unit tests..."
        - yarn run test
        - echo "All unit tests completed with no error."

staging:
    stage: trigger
    needs:
      - lint-job
      - test-job
    trigger:
        include: ".gitlab/staging.yml"
    only:
        - staging

production:
    stage: trigger
    needs:
      - lint-job
      - test-job
    trigger:
        include: ".gitlab/production.yml"
    only:
        - main

pages:
    image: alpine:latest
    stage: pages-deploy
    needs:
      - build-job
    variables:
        GIT_STRATEGY: none
    script:
        - echo "Deploying public/ directory..."
        - mv build public
        - echo "Deployed public/ directory..."
    artifacts:
        paths:
            - public
    only:
        - main
