image: node:16.13.1

stages:
    - install
    - build
    - lint and test
    - trigger

cache:
    paths:
        - node_modules/

install-job:
    stage: install
    script:
        - echo "Installing dependencies..."
        - yarn install
        - echo "Installed dependencies."

build-job:
    stage: build
    script:
        - echo "Compiling *.md"
        - yarn build
        - echo "Compiled *.md to build/*.html."
    artifacts:
        paths:
            - build/ 
 
lint-job:
    stage: lint and test
    needs: [build-job]
    script:
        - echo "Linting code..."
        - yarn lint
        - echo "No lint issues found."

test-job:
    stage: lint and test
    needs: [build-job]
    script:
        - echo "Running unit tests..."
        - yarn test
        - echo "All unit tests completed with no error."

staging:
    stage: trigger
    needs:
      - lint-job
      - test-job
    trigger:
        include: ".gitlab/staging.yml"
    only:
        - staging

production:
    stage: trigger
    needs:
      - lint-job
      - test-job
    trigger:
        include: ".gitlab/production.yml"
    only:
        - main

pages:
    stage: trigger
    needs:
      - lint-job
      - test-job
      - job: build-job
        artifacts: true
    trigger:
        include: ".gitlab/pages.yml"
    only:
        - main
