image: alpine:latest

stages:
    - pages-deploy
  
pages:
    stage: pages-deploy
    variables:
        GIT_STRATEGY: none
    script:
        - echo "Deploying public/ directory..."
        - cp build public
        - echo "Deployed public/ directory..."
    artifacts:
        paths:
            - public
    only:
        - main