image: ruby:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

production-job:
    type: deploy
    script:
        - echo "[Production] Deploying to heroku..."
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
        - echo "[Production] Deployed to heroku."
    only:
        - main
