image: ruby:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - production
    - pages-deploy

production-heroku-job:
    type: deploy
    stage: production
    script:
        - echo "[Production] Deploying to heroku..."
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
        - echo "[Production] Deployed to heroku."
    only:
        - main

production-gae-job:
    type: deploy
    image: google/cloud-sdk:alpine
    stage: production
    script:
        - echo "[Production] Deploying to gae..."
        - echo $SERVICE_ACCOUNT > SERVICE_ACCOUNT.json
        - gcloud auth activate-service-account --key-file SERVICE_ACCOUNT.json
        - gcloud --quiet --project $GAE_ID app deploy app.yaml dispatch.yaml
        - echo "[Production] Deployed to gae."
    only:
        - main
        
pages:
    stage: pages-deploy
    variables:
        GIT_STRATEGY: none
    script:
        - echo "Deploying public/ directory..."
        - cp build public
        - echo "Deployed public/ directory..."
    artifacts:
        paths:
            - public
    only:
        - main
