image: ruby:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

staging-job:
    type: deploy
    script:
        - echo "[Staging] Deploying to heroku..."
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
        - echo "[Staging] Deployed to heroku."
    only:
        - staging