image: ruby:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - staging

staging-heroku-job:
    type: deploy
    stage: staging
    script:
        - echo "[Staging] Deploying to heroku..."
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
        - echo "[Staging] Deployed to heroku."
    only:
        - staging

staging-gae-job:
    type: deploy
    image: google/cloud-sdk:slim
    stage: staging
    script:
        - echo "[Staging] Deploying to gae..."
        - echo $SERVICE_ACCOUNT > SERVICE_ACCOUNT.json
        - gcloud auth activate-service-account --key-file SERVICE_ACCOUNT.json
        - gcloud --quiet --project $GAE_ID app deploy staging.yaml dispatch.yaml
        - echo "[Staging] Deployed to gae."
    only:
        - staging
